from __future__ import annotations

import json
from datetime import datetime

import markdown2

from . import database


def _fmt_json(data: dict) -> str:
    return "```json\n" + json.dumps(data, indent=2, ensure_ascii=False)[:4000] + "\n```"


def build_markdown_report(case_id: str) -> str:
    case = database.get_case(case_id)
    if not case:
        raise ValueError("Case not found")
    findings = database.list_findings(case_id)
    notes = database.list_notes(case_id)

    lines = []
    lines.append(f"# Case Report: {case['name']}")
    lines.append("")
    lines.append(f"- **Case ID:** `{case['id']}`")
    lines.append(f"- **Investigator:** {case.get('investigator') or '_unspecified_'}")
    lines.append(f"- **Status:** {case['status']}")
    lines.append(f"- **Created:** {case['created_at']}")
    lines.append(f"- **Last updated:** {case['updated_at']}")
    lines.append(f"- **Generated:** {datetime.utcnow().isoformat(timespec='seconds')}Z")
    if case.get("description"):
        lines.append("")
        lines.append(f"**Description:** {case['description']}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"## Summary")
    lines.append(f"- Total logged findings: **{len(findings)}**")
    tool_counts = {}
    for f in findings:
        tool_counts[f["tool"]] = tool_counts.get(f["tool"], 0) + 1
    for tool, n in sorted(tool_counts.items()):
        lines.append(f"  - {tool}: {n}")
    lines.append("")

    if notes:
        lines.append("## Investigator Notes")
        for n in notes:
            lines.append(f"- _{n['created_at']}_ — {n['note']}")
        lines.append("")

    lines.append("## Findings Log")
    lines.append("")
    for i, f in enumerate(findings, 1):
        lines.append(f"### {i}. [{f['tool']}] {f['subject']} ({f['subject_type']})")
        lines.append(f"- **Logged:** {f['created_at']}")
        lines.append(f"- **Status:** {f['status']}")
        if f.get("summary"):
            lines.append(f"- **Summary:** {f['summary']}")
        lines.append("")
        lines.append("<details><summary>Raw data</summary>")
        lines.append("")
        lines.append(_fmt_json(f["data"]))
        lines.append("")
        lines.append("</details>")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by RAWS, a self-hosted, read-only OSINT workstation. "
                  "All data derived from public, read-only sources at time of lookup._")

    return "\n".join(lines)


def build_pdf_report(case_id: str) -> bytes:
    from weasyprint import HTML  # imported lazily - heavier dependency

    md_text = build_markdown_report(case_id)
    html_body = markdown2.markdown(md_text, extras=["fenced-code-blocks", "tables"])
    html_doc = f"""
    <html>
    <head>
    <meta charset="utf-8">
    <style>
        body {{ font-family: 'Georgia', 'Times New Roman', serif; color: #1a1a1a; line-height: 1.5; margin: 2.5cm; }}
        h1 {{ border-bottom: 3px solid #8b1a1a; padding-bottom: 8px; }}
        h2 {{ border-bottom: 1px solid #999; padding-bottom: 4px; margin-top: 28px; }}
        h3 {{ color: #8b1a1a; margin-top: 20px; }}
        code, pre {{ background: #f4f1ea; font-family: 'Courier New', monospace; font-size: 10px; }}
        pre {{ padding: 8px; border-left: 3px solid #8b1a1a; overflow-x: auto; white-space: pre-wrap; word-break: break-word; }}
        details {{ margin-bottom: 10px; }}
        summary {{ cursor: pointer; font-weight: bold; color: #444; }}
        table {{ border-collapse: collapse; width: 100%; }}
        td, th {{ border: 1px solid #ccc; padding: 4px 8px; }}
    </style>
    </head>
    <body>{html_body}</body>
    </html>
    """
    return HTML(string=html_doc).write_pdf()
